### ISSUE TITLE
Live-reload solution?

### ISSUE THREAD

**Issue by jaredpalmer** [HumbleSpark/sambell#3]
- browser-sync (took about 8 seconds when i tried this)
- webpack-http-proxy-middleware
- webpack-live-reload-plugin (also took wayyy too long)

Thoughts?

**Comment by ndreckshage** [comment]
@jaredpalmer I don't use live-reload (personal preference), but happy to add it in if you want to submit a PR. As to why it takes long - not sure. Nothing magical is going on with this repo, just a webpack config that runs 2x, creating client & server output. Do you have a branch / snippets I could see?

**Comment by ndreckshage** [comment]
The way create react app does it should work. No reason it should be any slower than create react app. https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpackDevServer.config.js

**Comment by jaredpalmer** [comment]
Install browser-sync globally, run sambell, open another terminal tab, and then run browser-sync from cli proxying from the correct port.

**Comment by ndreckshage** [comment]
Feel free to investigate, I don't have time to look into this now. I'd support the way create react app does it, probably nothing requiring global install.
